[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=1001
aors=1001
transport=transport-udp

[1001]
type=auth
auth_type=userpass
password=1234
username=1001

[1001]
type=aor
max_contacts=1
qualify_frequency=60

[1002]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=1002
aors=1002
transport=transport-udp

[1002]
type=auth
auth_type=userpass
password=1234
username=1002

[1002]
type=aor
max_contacts=1
qualify_frequency=60

[1003]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=1003
aors=1003
transport=transport-udp

[1003]
type=auth
auth_type=userpass
password=1234
username=1003

[1003]
type=aor
max_contacts=1
qualify_frequency=60
